Very minor updates to images
YoshinoriN/docker-gitbucket-orchestration pull request #32
Opened 2021-02-02 22:32 UTC by catskillmarina

Very minor updates to images just for me to use. Added space for sslkeys as well

2021-02-03 13:18 UTC, YoshinoriN requested changes
@catskillmarina

Thank you very much :)
Would you please update the badge on README? Like below.

> 9bf2e8af9765ae45eb64e2e528be59c9d96409e9

 I forgot to update it when update 4.35.0

2021-02-05 17:24 UTC, catskillmarina commented
I'm not sure what you mean by a 'badge'. What do you need me to do.

2021-02-06 09:02 UTC, YoshinoriN commented on README.md
> +![](https://img.shields.io/badge/GitBucket-v4.36.0-blue.svg)
Sorry so lack of explanation.

I put `GitBucket versions badge (label) ` to README like below.

![badge](https://user-images.githubusercontent.com/11273093/107113781-8037d500-68a4-11eb-8364-eb318f612e66.jpg)

And its version is the same with the GitBucket version.
So, would you please change like below?

```diff
- ![](https://img.shields.io/badge/GitBucket-v4.36.0-blue.svg)
+ ![](https://img.shields.io/badge/GitBucket-v4.35.3-blue.svg)
```

Thank you :)

2021-02-06 18:47 UTC, catskillmarina commented
Badge is updated as you requested.

2021-02-07 10:27 UTC, YoshinoriN approved these changes
Thank you :)

2021-02-07 10:27 UTC, merged